[package]
name = "tonlibjson-tokio"
version = "0.1.0"
edition = "2021"
authors = ["Andrei Kostylev <a.kostylev@pm.me>"]

[dependencies]
tonlibjson-rs = { path = "../tonlibjson-rs" }
anyhow = "1.0.58"
serde = { version = "1.0.138", features = ["serde_derive"] }
serde_json = "1.0.79"
tokio = { version = "1.19.2", features = ["rt-multi-thread", "sync", "macros", "time", "rt"] }
futures = "0.3.21"
dashmap = "5.3.4"
uuid = { version = "1.1.2", features = ["v4", "fast-rng"] }
tower = { version = "0.4.13", features = ["full"] }
pin-project = "1.0.10"
