[package]
name = "tonlibjson-rs"
version = "0.1.0"
edition = "2021"
authors = ["Andrei Kostylev <a.kostylev@pm.me>"]

[dependencies]
libc = "0.2.125"
anyhow = "1.0.60"

[build-dependencies]
cmake = "0.1.48"
pkg-config = "0.3.25"
