[package]
name = "tonlibjson-rs"
version = "0.1.0"
edition = "2021"
authors = ["Andrei Kostylev <a.kostylev@pm.me>"]

[dependencies]
libc = "0.2.137"
anyhow = { workspace = true }

[build-dependencies]
cmake = "0.1.49"
pkg-config = "0.3.25"

[dev-dependencies]
procinfo = "0.4.2"
